export * from './Code'
export * from './Dial'
export * from './Exit'
export * from './Hamburger'
export * from './Home'
export * from './Github'
export * from './Location'
export * from './Lock'
export * from './Mail'
export * from './Map'
export * from './Settings'
export * from './Time'
export * from './User'

// Allow for Icon.Props
export type { IconProps as Props } from './icons.types'
